### ISSUE TITLE
Ignore these youtubers in fafbot (SWTOR casters)

### ISSUE THREAD

**Issue by Sheeo** [FAForever/QAI#1]
swcallow98 Chaotic3volution Blizofoz45 MultiAwesome123 TheDkgr4y MrSuperDjavo elitenz imsobuffed devilfiresmile666 acort14 aagrippaa suicune2001 MarcanOlsson elitenichemarketing Rayfinders TheGrahamAker DathanielTDK syfy88man KidLee3ASF swtorPaladin BobaVoll hale32225 Shotgunchief38 maxulic Jedidavie0804 Zedcreek legoboy4567 TDGMMO FluffyNinjaLlama KiethSomataw99 SideStrafe SilveliaDarkmoon FastSoulSlayer pokemonmaster9416 ArtemysKnigh

**Comment by Sheeo** [comment]
Could be done in tandem with #3

**Comment by JeroenDeDauw** [comment]
I'm curious. Why should these be ignored and how was this list generated?

**Comment by Sheeo** [comment]
These are known casters of Star Wars: The Old Republic.

A search to yield these with good certainty would be a good idea as well.

**Comment by JeroenDeDauw** [comment]
Thinking about it, this feature seems like a nice small thing to get started with contributing something to FAF. I'll have a go at it

**Comment by JeroenDeDauw** [comment]
#5 needs to be tackled first. Once I know how to run the code, I can look into adding a test setup as per #4, after which I can proceed with the youtuber exclusion modification

**Comment by JeroenDeDauw** [comment]
I started working on this now

**Comment by JeroenDeDauw** [comment]
Implemented in https://github.com/FAForever/fafbot/pull/26 (see the last commit there)
