### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by Sheeo** [FAForever/QAI#16]
If fafbot could post messages to slack and take commands from it, he would potentially be very useful for moderators.

**Comment by JeroenDeDauw** [comment]
https://api.slack.com/

**Comment by IDragonfire** [comment]
https://api.slack.com/

**Comment by Sheeo** [comment]
@JeroenDeDauw well it already takes commands from IRC :)

**Comment by JeroenDeDauw** [comment]
Oh right. Information retrieval commands make sense. I was thinking you meant the kind of commands that would modify state somewhere else.

**Comment by Brutus5000** [comment]
We're not using Slack anymore.
