### ISSUE TITLE
Install missing dependencies on TravisCI

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/QAI#23]
The TravisCI build currently fails since not all dependencies are installed (PySide is missing). Example error: https://travis-ci.org/FAForever/fafbot/builds/57166228

Installing PySide as follows

```
pip install PySide
python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
```

... results in this error: https://travis-ci.org/FAForever/fafbot/builds/57168203

**Comment by JeroenDeDauw** [comment]
> The TravisCI build currently fails

This is no longer the case since I split of the code that's being tested in such a way that it no longer depends on these missing dependencies.

**Comment by Brutus5000** [comment]
Closed due to ancientivity
