### ISSUE TITLE
Blacklist for blocking youtube spam for fafbot

### ISSUE THREAD

**Issue by Cheyans** [FAForever/QAI#3]
Feel free to add more in the comments

Crack
Free
Download
Pirate
Compressed
Zip
Rar
Full
repack
License
key

**Comment by JeroenDeDauw** [comment]
There is spam on youtube that has "Forged Alliance" in its title or description?!

**Comment by JeroenDeDauw** [comment]
We might not want to block descriptions that include something like:

You can **download** the **full** FAF client for **free** at ...

**Comment by MattDeering** [comment]
Star Wars, Old Republic or something similar. There is a raid titled forged alliance which occasionally pops up.

**Comment by Sheeo** [comment]
I think we should initially just block videos that feature these keywords in the title -- I don't think going for the description is necessary.

**Comment by JeroenDeDauw** [comment]
**Pirates of Setons**

**Compressed T3 action**

**Cracking turtle noobs**

Banning single worlds, even from titles, has a good potential for false positives

**Comment by Cheyans** [comment]
How about have users be able to !report one of the posted links and when 2 or 3 users also report the link, the youtube video is ignored and the channel is blacklisted.

**Comment by JeroenDeDauw** [comment]
That is a lot harder to implement, and opens up a new avenue of abuse. Popular streamers will have more than 3 haters, so they can easily get their channel blacklisted.

**Comment by Bra1nwash3d** [comment]
fixed a while ago in https://github.com/FAForever/QAI/commit/783a23b1ae21c67134d72224692f3893b842481c
