### ISSUE TITLE
Sheeo, the whole kick people and spam taunts with QAI is dumb. Can we tone it down?

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/QAI#33]
Read above.

**Comment by Sheeo** [comment]
The rage meter needs to be limited by (channel, user) instead of being a global.

**Comment by Bra1nwash3d** [comment]
https://github.com/FAForever/QAI/pull/35
changed the "nobody is streaming" taunt by a message, that there is nobody streaming
changed the rage meter so that it goes up on players individually
