### ISSUE TITLE
QAI's search for casts isn't working.

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/QAI#38]
Some casts are called "Forged Alliance" show up on this list: https://www.youtube.com/results?search_query=forged+alliance&search_sort=video_date_uploaded

They are not shown by !casts however.

**Comment by Sheeo** [comment]
Because !casts uses safesearch. Google has a tutorial somewhere about how to make your videos appear there.

**Comment by VoRGoR** [comment]
Searched for a looong time. Asked several people who have their casts showing up. 
No one has any idea what you're talking about.

**Comment by Sheeo** [comment]
I can't actually find their tutorial. This is the only relevant page https://support.google.com/websearch/answer/510?vid=1-635757506840241630-488876766.

We need to keep it on to not have QAI link inappropriate content. Perhaps we could use the 'moderate' setting, though.

**Comment by VoRGoR** [comment]
I don't think it's working. 

[VoR]Gorton: 
!casts
QAI 
orbitalpotato: Supreme Commander Forged Alliance - 3 - Bombing Raids! - 08/19/15: http://youtu.be/qJr0WX8axXw

That's two days ago : there are roughly 10 or more casts missing, from casters that have been seen before.

This video here: https://www.youtube.com/watch?v=ez46eYWzjMU has nothing bad in the safesearch, it can be searched by strict, I tested it. It's not showing up in !casts.

**Comment by Exotic-Retard** [comment]
it seems that it doesn't pick up "Supreme Commander Forged Alliance" in the title, it needs a : after the commander, or it doesn't work. at least that's what i think

**Comment by VoRGoR** [comment]
"Forged Alliance" by itself it what should be triggering it.

**Comment by speed2CZ** [comment]
it ignores my videos I have Supreme Commander: Forged Alliance in title and tagged it as well with everything possible.
What about some whitelist of channels which to always show?
