### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/QAI#4]
This repository currently does not appear to have any tests. Adding a few basic integration tests would already provide a lot of value. And having testing infrastructure in place then makes it easier to contribute new code or modification and have that unit tested right away.

**Comment by JeroenDeDauw** [comment]
Started tackling this in https://github.com/FAForever/fafbot/issues/4

**Comment by JeroenDeDauw** [comment]
Closing this now as tests are being added in https://github.com/FAForever/fafbot/pull/22, so there seems little point in keeping this around.

**Comment by Brutus5000** [comment]
We have added some test now. If you thought about tests regarding specific topics, please add more detailled information in a new issue.
